name: Run Telegram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # har 30 minute me run hoga

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          HOLLYWOOD_CHANNEL: ${{ secrets.HOLLYWOOD_CHANNEL }}
          TOLLYWOOD_CHANNEL: ${{ secrets.TOLLYWOOD_CHANNEL }}
          BOLLYWOOD_CHANNEL: ${{ secrets.BOLLYWOOD_CHANNEL }}
